---
title: "multivariate linear regressions"
output: md_document
---

get & prep data
```{r get & prep data}
library(car)
library(hash)
library(MASS)
library(MESS)
library(plyr)
library(ROCR)
data <- read.csv('../data/CPP_data_all.csv', header=TRUE)
smq <- read.csv('../data/SMQ.csv', header=TRUE)
smq$smq_id <- (18 - smq$smq_id) / 6
data <- ddply(data, .(URSI, SM_dx), summarize,
              Turn_Count=sum(Turn_Count),
              Child_Voc_Count=sum(Child_Voc_Count),
              Child_Voc_Duration=sum(Child_Voc_Duration),
              Child_NonVoc_Duration=sum(Child_NonVoc_Duration),
              Average_SignalLevel=mean(Average_SignalLevel),
              Peak_SignalLevel=max(Peak_SignalLevel)
              )
data <- merge(data, smq, by="URSI", all=TRUE)
remove(smq)
# invert SMQ for severity
data$smq_as <- 3 - data$smq_as
data$smq_hf <- 3 - data$smq_hf
data$smq_ss <- 3 - data$smq_ss
data$smq_id <- 3 - data$smq_id
data$SM_dx <- factor(data$SM_dx)
smq_data <- data[complete.cases(data),]
```

multivariate forward linear regression for SMQ
```{r forward regression for SMQ}
smq <- c("smq_as", "smq_hf", "smq_ss", "smq_id")
fsmq_predicted <- vector()
fsmq_actual <- vector()
fsmq_models <- vector()
fsmq_predictors <- hash()
kii <- vector()
for(k in 1:4){
  predicted <- vector()
  actual <- vector()
  models <- vector()
  predictors <- hash()
  for(i in 1:nrow(smq_data)){
    train <- smq_data[-i,]
    test <- smq_data[i,]
    model <- step(lm(get(smq[k])~1, data=train, na.action=na.omit),
             direction='forward', scope=~Child_Voc_Count+Turn_Count+
             Child_Voc_Duration+Child_NonVoc_Duration+Average_SignalLevel+
             Peak_SignalLevel)
    for(j in 1:length(names(model$coefficients))){
      if(has.key(names(model$coefficients)[[j]], predictors)){
        .set(predictors, names(model$coefficients)[[j]],
             as.numeric(predictors[[names(model$coefficients)[[j]]]])+ 1)
      }else{
        .set(predictors, names(model$coefficients)[[j]], 1)
      }
    }
    models <- c(models, model)
    predicted <- c(predicted, predict(model, test))
    actual <- c(actual, test[[smq[k]]])
    remove(j)
    remove(train)
    remove(test)
  }
  fsmq_models <- c(fsmq_models, models)
  fsmq_predicted <- c(fsmq_predicted, predicted)
  fsmq_actual <- c(fsmq_actual, actual)
  .set(fsmq_predictors, smq[k], predictors)
}
print(fsmq_predictors)
remove(i)
```

```{r plot for forward regression predicting SMQ}
par(oma=c(3,3,0,0),mar=c(3,3,2,2),mfrow=c(2,2), pty="s")
plot(matrix(fsmq_predicted, ncol=4)[,1],matrix(fsmq_actual, ncol=4)[,1], type='p',
     xlab="", ylab=paste("R\u00b2=", 1-(sum((matrix(fsmq_actual, ncol=4)[,1]-matrix(fsmq_predicted, ncol=4)[,1])^2)/sum((matrix(fsmq_actual, ncol=4)[,1]-mean(matrix(fsmq_actual, ncol=4)[,1]))^2))), xlim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,1], matrix(fsmq_actual, ncol=4)[,1]))), ylim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,1], matrix(fsmq_actual, ncol=4)[,1]))), asp=1, main="at school")
abline(lm(as.numeric(matrix(fsmq_actual, ncol=4)[,1])~as.numeric(matrix(fsmq_predicted, ncol=4)[,1])))
plot(matrix(fsmq_predicted, ncol=4)[,2],matrix(fsmq_actual, ncol=4)[,2], type='p',
     xlab="", xlim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,2], matrix(fsmq_actual, ncol=4)[,2]))), ylim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,2], matrix(fsmq_actual, ncol=4)[,2]))), asp=1, main="home / family", ylab=paste("R\u00b2=", 1-(sum((matrix(fsmq_actual, ncol=4)[,2]-matrix(fsmq_predicted, ncol=4)[,2])^2)/sum((matrix(fsmq_actual, ncol=4)[,2]-mean(matrix(fsmq_actual, ncol=4)[,2]))^2))))
abline(lm(as.numeric(matrix(fsmq_actual, ncol=4)[,2])~as.numeric(matrix(fsmq_predicted, ncol=4)[,2])))
plot(matrix(fsmq_predicted, ncol=4)[,3],matrix(fsmq_actual, ncol=4)[,3], type='p',
     xlab="", xlim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,3], matrix(fsmq_actual, ncol=4)[,3]))), ylim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,3], matrix(fsmq_actual, ncol=4)[,3]))), asp=1, main="in social situations\n(outside of school)", ylab=paste("R\u00b2=", 1-(sum((matrix(fsmq_actual, ncol=4)[,3]-matrix(fsmq_predicted, ncol=4)[,3])^2)/sum((matrix(fsmq_actual, ncol=4)[,3]-mean(matrix(fsmq_actual, ncol=4)[,3]))^2))))
abline(lm(as.numeric(matrix(fsmq_actual, ncol=4)[,3])~as.numeric(matrix(fsmq_predicted, ncol=4)[,3])))
plot(matrix(fsmq_predicted, ncol=4)[,4],matrix(fsmq_actual, ncol=4)[,4], type='p',
     xlab="", xlim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,4], matrix(fsmq_actual, ncol=4)[,4]))), ylim=c(0,max(c(matrix(fsmq_predicted, ncol=4)[,4], matrix(fsmq_actual, ncol=4)[,4]))), asp=1, main="interference / distress", ylab=paste("R\u00b2=", 1-(sum((matrix(fsmq_actual, ncol=4)[,4]-matrix(fsmq_predicted, ncol=4)[,4])^2)/sum((matrix(fsmq_actual, ncol=4)[,4]-mean(matrix(fsmq_actual, ncol=4)[,4]))^2))))
abline(lm(as.numeric(matrix(fsmq_actual, ncol=4)[,4])~as.numeric(matrix(fsmq_predicted, ncol=4)[,4])))
mtext(text="Predicted SMQ symptom severity",side=1,line=0,outer=TRUE)
mtext(text="Reported SMQ symptom severity",side=2,line=0,outer=TRUE)
```
