---
title: "logistical regressions with ROC curve"
output: md_document
---

get & prep data
```{r get & prep data}
library(car)
library(hash)
library(MASS)
library(MESS)
library(plyr)
library(ROCR)
data <- read.csv('../data/CPP_data_all.csv', header=TRUE)
smq <- read.csv('../data/SMQ.csv', header=TRUE)
smq$smq_id <- (18 - smq$smq_id) / 6
data <- ddply(data, .(URSI, SM_dx), summarize,
              Turn_Count=sum(Turn_Count),
              Child_Voc_Count=sum(Child_Voc_Count),
              Child_Voc_Duration=sum(Child_Voc_Duration),
              Child_NonVoc_Duration=sum(Child_NonVoc_Duration),
              Average_SignalLevel=mean(Average_SignalLevel),
              Peak_SignalLevel=max(Peak_SignalLevel)
              )
data <- merge(data, smq, by="URSI", all=TRUE)
remove(smq)
# invert SMQ for severity
data$smq_as <- 3 - data$smq_as
data$smq_hf <- 3 - data$smq_hf
data$smq_ss <- 3 - data$smq_ss
data$smq_id <- 3 - data$smq_id
data$SM_dx <- factor(data$SM_dx)
smq_data <- data[complete.cases(data),]
```

logistical regression predicting SM dx
```{r logistical regression predicting SM dx}
lreg_fp <- vector()
lreg_tp <- vector()
lreg_predictors <- hash()
for(i in 1:nrow(data)){
  train <- data[-i,]
  test <- data[i,]
  lreg_model <- glm(SM_dx~Child_Voc_Count+Turn_Count+Child_Voc_Duration+Child_NonVoc_Duration+
                Average_SignalLevel+Peak_SignalLevel, family=binomial(link='logit'), data=train,
                na.action=na.pass)
  lreg_p <- predict(lreg_model, test, "response")
  lreg_pr <- prediction(lreg_p, test$SM_dx)
  lreg_fp <- c(lreg_fp, lreg_pr@fp[[1]][[2]])
  lreg_tp <- c(lreg_tp, lreg_pr@tp[[1]][[2]])
  for(j in 1:length(names(lreg_model$coefficients))){
    if(has.key(names(lreg_model$coefficients)[[j]], lreg_predictors)){
      .set(lreg_predictors, names(lreg_model$coefficients)[[j]],
           as.numeric(lreg_predictors[[names(lreg_model$coefficients)[[j]]]]) + 1)
    }else{
      .set(lreg_predictors, names(lreg_model$coefficients)[[j]], 1)
    }
  }
  remove(j)
  print(summary(lreg_model))
  print(anova(lreg_model, test="Chisq"))
  remove(train)
  remove(test)
}
remove(i)
print(lreg_predictors)
```

```{r ROC for logistical regression predicting SM dx}
par(pty="s")
plot(c(0,cumsum(lreg_fp)/sum(lreg_fp),1), c(0,cumsum(lreg_tp)/sum(lreg_tp),1), type='l', xlab=
     "False positive rate", ylab="True positive rate", xlim=c(0,1), ylim=c(0,1), asp=1)
text(0.6, 0.2, labels=paste("auc: ", auc(cumsum(lreg_fp)/sum(lreg_fp), cumsum(lreg_tp)/sum(lreg_tp))))
```

logistical forward regression predicting SM dx
```{r logistical forward regression predicting SM dx}
lfreg_fp <- vector()
lfreg_tp <- vector()
lfreg_predictors <- hash()
for(i in 1:nrow(data)){
  train <- data[-i,]
  test <- data[i,]
  lfreg_model <- stepAIC(glm(SM_dx ~ 1, family=binomial(link='logit'), data=train, na.action=na.pass),
                direction='forward', scope=~Child_Voc_Count+Turn_Count+Child_Voc_Duration+
                Child_NonVoc_Duration+Average_SignalLevel+Peak_SignalLevel)
  lfreg_p <- predict(lfreg_model, test, "response")
  lfreg_pr <- prediction(lfreg_p, test$SM_dx)
  lfreg_fp <- c(lfreg_fp, lfreg_pr@fp[[1]][[2]])
  lfreg_tp <- c(lfreg_tp, lfreg_pr@tp[[1]][[2]])
  print(summary(lreg_model))
  print(anova(lreg_model, test="Chisq"))
  for(j in 1:length(names(lfreg_model$coefficients))){
    if(has.key(names(lfreg_model$coefficients)[[j]], lfreg_predictors)){
      .set(lfreg_predictors, names(lfreg_model$coefficients)[[j]],
           as.numeric(lfreg_predictors[[names(lfreg_model$coefficients)[[j]]]]) + 1)
    }else{
      .set(lfreg_predictors, names(lfreg_model$coefficients)[[j]], 1)
    }
  }
  remove(j)
  remove(train)
  remove(test)
}
remove(i)
print(lfreg_predictors)
```

```{r ROC for logistical forward regression predicting SM dx}
par(pty="s")
plot(c(0,cumsum(lfreg_fp)/sum(lfreg_fp),1), c(0,cumsum(lfreg_tp)/sum(lfreg_tp),1), type='l', xlab=
     "False positive rate", ylab="True positive rate", asp=1)
text(0.6, 0.2, labels=paste("auc: ", auc(cumsum(lfreg_fp)/sum(lfreg_fp), cumsum(lfreg_tp)/sum(lfreg_tp))))
```

forward regression for SMQ
```{r forward regression for SMQ}
fsmq_predicted <- vector()
fsmq_actual <- vector()
fsmq_models <- vector()
fsmq_predictors <- hash()
for(i in 1:nrow(smq_data)){
  train <- smq_data[-i,]
  test <- smq_data[i,]
  fsmq_model <- step(lm(smq_as+smq_hf+smq_ss+smq_id~1, data=train, na.action=na.omit),
                direction='forward', scope=~Child_Voc_Count+Turn_Count+Child_Voc_Duration+
                Child_NonVoc_Duration+Average_SignalLevel+Peak_SignalLevel)
  print(summary(fsmq_model))
  print(fsmq_model$anova)
  avPlots(fsmq_model)
  fsmq_predicted <- c(fsmq_predicted, predict(fsmq_model, test))
  fsmq_actual <- c(fsmq_actual, test$smq_as+test$smq_hf+test$smq_ss+test$smq_id)
  fsmq_models <- c(fsmq_models, fsmq_model)
  for(j in 1:length(names(fsmq_model$coefficients))){
    if(has.key(names(fsmq_model$coefficients)[[j]], fsmq_predictors)){
      .set(fsmq_predictors, names(fsmq_model$coefficients)[[j]],
           as.numeric(fsmq_predictors[[names(fsmq_model$coefficients)[[j]]]]) + 1)
    }else{
      .set(fsmq_predictors, names(fsmq_model$coefficients)[[j]], 1)
    }
  }
  remove(j)
  remove(train)
  remove(test)
}
print(fsmq_predictors)
remove(i)
```

```{r plot for forward regression predicting SMQ}
par(pty="s")
plot(fsmq_predicted, fsmq_actual, type='p',
     xlab="Predicted SMQ symptom severity",ylab="Reported SMQ symptom severity", asp=1, sub=paste("Pearson's r=",  cor(as.numeric(fsmq_predicted), as.numeric(fsmq_actual), method="pearson"), "; R\u00b2: ", 1-(sum((fsmq_actual-fsmq_predicted)^2)/sum((fsmq_actual-mean(fsmq_actual))^2))))
abline(lm(as.numeric(fsmq_actual)~as.numeric(fsmq_predicted)))
```

```{r}
plot(smq_as+smq_hf+smq_ss+smq_id ~ Child_Voc_Count, data=smq_data)
abline(lm(smq_as+smq_hf+smq_ss+smq_id ~ Child_Voc_Count, data=smq_data))
```

```{r}
plot(smq_as+smq_hf+smq_ss+smq_id ~ Child_Voc_Duration, data=smq_data)
abline(lm(smq_as+smq_hf+smq_ss+smq_id ~ Child_Voc_Duration, data=smq_data))
```

```{r}
plot(smq_as+smq_hf+smq_ss+smq_id ~ Average_SignalLevel, data=smq_data)
abline(lm(smq_as+smq_hf+smq_ss+smq_id ~ Average_SignalLevel, data=smq_data))
```